pipeline {
    agent any
    stages {
        stage('Trigger Template') {
            steps {
                script {
                    // Assuming you are using a template catalog to trigger the template
                    pipelineTemplate(name: 'Trigger-Remote')
                }
            }
        }
    }
}
