pipeline {
    agent any
    stages {
        stage('Trigger Template') {
            steps {
                script {
                    // Assuming you are using a template catalog to trigger the template
                    triggerTemplate(name: 'my-pipeline-template', parameters: [])
                }
            }
        }
    }
}
