# template.yaml
apiVersion: v1
kind: Pipeline
metadata:
  name: my-pipeline-template
spec:
  pipeline:
    agent:
      label: "linux"
    stages:
      - stage: "Build"
        steps:
          - script: |
              echo "Building the project..."
              # Add your build steps here
      - stage: "Deploy"
        steps:
          - script: |
              echo "Deploying the project..."
              # Add your deployment steps here
      - stage: "Trigger Downstream Job"
        steps:
          - script: |
              echo "Triggering downstream job..."
              build job: 'test-pipeline', wait: false
