type: pipeline-template
version: 1
name: Trigger Remote
description: Quarkus Maven Template 2
stages:
 - stage: "Trigger Downstream Job"
   steps:
    - script: |
       echo "Triggering downstream job..."
       build job: 'test-pipeline', wait: false
