pipeline {
    agent any
    stages {
        stage('Build') {
          steps { 
              script {
                  build job: 'http://localhost:8081/job/test-pipeline', wait:false
              }

          }
        }
    }
}
