type: pipeline-template
version: 1

name: Quarkus Maven Template
description: Quarkus Maven Template
parameters:
  - name: previewEnvHostname
    displayName: Preview env hostname
    defaultValue: foo
  - name: emailRecipient
    displayName: Email address for build notifications
    defaultValue: foo@bar.com
stages:
  - name: TriggerDownstream
    type: job
    jobs:
      - name: TriggerDownstreamJob
        type: trigger
        trigger_jobs:
          - job_url: "http://localhost:8081/job/test-pipeline/"
