type: pipeline-template
version: 1

name: Quarkus Maven Template
description: Quarkus Maven Template
stages:
  - name: TriggerDownstream
    type: job
    jobs:
      - name: TriggerDownstreamJob
        type: trigger
        trigger_jobs:
          - job_name: "test-pipeline" wait: false
